<?php

/**
 * BaseSport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $sport
 * @property boolean $active
 * @property Doctrine_Collection $Competition
 * 
 * @method string              getSport()       Returns the current record's "sport" value
 * @method boolean             getActive()      Returns the current record's "active" value
 * @method Doctrine_Collection getCompetition() Returns the current record's "Competition" collection
 * @method Sport               setSport()       Sets the current record's "sport" value
 * @method Sport               setActive()      Sets the current record's "active" value
 * @method Sport               setCompetition() Sets the current record's "Competition" collection
 * 
 * @package    sport-statistics
 * @subpackage model
 * @author     Cristian Radulescu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sport');
        $this->hasColumn('sport', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Competition', array(
             'local' => 'id',
             'foreign' => 'sport_id'));
    }
}