<?php

/**
 * BaseFixture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $competition_id
 * @property integer $round
 * @property string $game
 * @property string $final_time
 * @property string $half_time
 * @property Competition $Competition
 * 
 * @method integer     getCompetitionId()  Returns the current record's "competition_id" value
 * @method integer     getRound()          Returns the current record's "round" value
 * @method string      getGame()           Returns the current record's "game" value
 * @method string      getFinalTime()      Returns the current record's "final_time" value
 * @method string      getHalfTime()       Returns the current record's "half_time" value
 * @method Competition getCompetition()    Returns the current record's "Competition" value
 * @method Fixture     setCompetitionId()  Sets the current record's "competition_id" value
 * @method Fixture     setRound()          Sets the current record's "round" value
 * @method Fixture     setGame()           Sets the current record's "game" value
 * @method Fixture     setFinalTime()      Sets the current record's "final_time" value
 * @method Fixture     setHalfTime()       Sets the current record's "half_time" value
 * @method Fixture     setCompetition()    Sets the current record's "Competition" value
 * 
 * @package    sport-statistics
 * @subpackage model
 * @author     Cristian Radulescu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFixture extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fixture');
        $this->hasColumn('competition_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('round', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('game', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('final_time', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('half_time', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Competition', array(
             'local' => 'competition_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}