default:
  http_metas:
    content-type: text/html

  metas:
    title:        Publicbet
    #description:  symfony project
    #keywords:     symfony, project
    language:     en
    #robots:       index, follow

  stylesheets:    [main.css]

  #javascripts:    []

  has_layout:     true
  layout:         layout
