<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Competition extends BaseCompetition
{
  /**
   * Retrieve statistics without null value
   *
   * @return array
   */
  public function getNotNullStatistics()
  {
    $statistics = $this->getStatistics()->toArray();
    foreach ($statistics as &$row_statistics)
    {
      foreach ($row_statistics as $key => $value)
      {
        if ($value == null)
        {
          unset($row_statistics[$key]);
        }
      }
    }

    return $statistics;
  }

  /**
   * Set active state
   *
   * @param boolean $active
   * @return boolean
   */
  public function activate($active = true)
  {
    $this->setActive($active);
    $this->save();
  }

  /**
   * Returns the toString representation
   * @return string
   */
  public function  __toString()
  {
    return $this->competition;
  }
}