<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompetitionTable extends Doctrine_Table
{
  /**
   * List table method
   *
   * @param Doctrine_Query $q
   * @return Doctrine_Query
   */
  public function retrieveBackendCompetitionList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias.'.Country c');
    $q->leftJoin($rootAlias.'.Sport s');
    $q->addOrderBy('s.sport');
    $q->addOrderBy('c.country');
    $q->addOrderBy('competition');
    
    return $q;
  }
}