<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Country extends BaseCountry
{
  public function isInternational()
  {
    if (in_array($this->getCountry(), array('International Clubs', 'International')))
    {
      return true;
    }
    return false;
  }

  /**
   * Returns the toString representation
   * @return string
   */
  public function  __toString()
  {
    return $this->country;
  }
}