<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatisticsTable extends Doctrine_Table
{
  /**
   * Remove old statistics for this competition
   *
   * @param int $competition_id
   * @return boolean
   */
  public function cleanup($competition_id)
  {
    $q = $this->createQuery('c')
      ->delete()
      ->andWhere('c.competition_id = ?', $competition_id);

    return $q->execute();
  }
}