generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Country
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          country
    with_doctrine_route:     1

    config:
      actions: ~
      fields:
        sport_id: { label: Sport }

      list:
        title: Countries
        display: [=country, _active]
        max_per_page: 15
        object_actions:
          competitions: { label: Show Competitions }

      filter:
        display: [country, active]
      form:    ~
      edit:    ~
      new:     ~
